"""add anchor_month to subscriptions

Revision ID: 5586f31a0822
Revises: a68c9747b1a2
Create Date: 2026-04-03 21:31:08.993742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5586f31a0822'
down_revision: Union[str, Sequence[str], None] = 'a68c9747b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('anchor_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'anchor_month')
    # ### end Alembic commands ###
